# DEPRECATED: This file has been superseded by docker/compose.prod.yml
#
# The production Docker Compose configuration is now at:
#   docker/compose.prod.yml
#
# To deploy:
#   cd /path/to/saghat
#   docker compose -f docker/compose.prod.yml up -d
#
# See deploy/README.md for full deployment instructions.
